// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4230.OCTO.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4230.OCTO.Robot;

/**
 *
 */
public class DriveSpeed extends Command {
	boolean toggleSlow = false;
	boolean toggleFast = false;
	boolean pressed1 = false;
	boolean pressed3 = false;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public DriveSpeed() {

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	}

	// Called just before this Command runs the first time
	protected void initialize() {

	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {

		if (Robot.oi.driver.getRawButton(3)) {
			if (pressed3 == false) {
				toggleSlow = !toggleSlow;
				pressed3 = true;
				if (toggleFast) {
					toggleFast = false;
				}
			}

		} else {
			pressed3 = false;
		}
		if (Robot.oi.driver.getRawButton(1)) {
			if (pressed1 == false) {
				toggleFast = !toggleFast;
				pressed1 = true;
				if (toggleSlow) {
					toggleSlow = false;
				}
			}
		} else {
			pressed1 = false;
		}

		if (toggleSlow) {
			TeleopDrive.maxSpeed = TeleopDrive.SLOW;
			// TeleopDrive.maxRotation = TeleopDrive.SLOW;
		} else if (toggleFast) {
			// TeleopDrive.maxRotation = TeleopDrive.FAST;
			TeleopDrive.maxSpeed = TeleopDrive.FAST;
		} else {
			TeleopDrive.maxSpeed = TeleopDrive.NORMAL;
			// TeleopDrive.maxRotation = TeleopDrive.NORMAL;
		}
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return false;
	}

	// Called once after isFinished returns true
	protected void end() {
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
	}
}
